### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by nemphys** [syscl/Sinetek-rtsx#5]
Hi, thank you for your efforts on this.
I am wondering if the project has been abandoned, since it's been a long time since the last commit.
I have a NUC8i7BEH with a Realtek card reader and it actually works using a Sinetek-rtsx.kext I found somewhere in a forum, with the only drawback that the read/write speeds are quite low.
I tried compiling the latest master revision from this repo and although the kext is built fine and is loaded, nothing happens when a card is inserted in the reader.
Any ideas?

**Comment by syscl** [comment]
@nemphys Yes, it is still alive.
